[project]
name = "dn_patchflashattention"
description = "A ComfyUI custom node that patches the attention mechanism to use Flash Attention 2, similar to how Patch Sage Attention KJ works in KJNodes."
version = "1.0.2"
license = {file = "LICENSE"} 

[project.urls]
Repository = "https://github.com/0xDELUXA/ComfyUI-DN_PatchFlashAttention"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/0xDELUXA/ComfyUI-DN_PatchFlashAttention/wiki"
"Bug Tracker" = "https://github.com/0xDELUXA/ComfyUI-DN_PatchFlashAttention/issues"

[tool.comfy]
PublisherId = "deluxa"
DisplayName = "ComfyUI-DN_PatchFlashAttention"
Icon = "https://avatars.githubusercontent.com/u/211159064"
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility

